remote_theme: ankitsultana/researcher@gem

title: Michael 'Misha' Rashkovetskyi
author: Michael Rashkovetskyi
description: Michael 'Misha' Rashkovetskyi's personal site
baseurl: ""

markdown: kramdown
ins_logo: ""

favicon: true
favicon_location: BTA.ico

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana/researcher"
footer_text: "Based on researcher jekyll template"

sass:
    style: compressed

nav:
 - name: "About"
   link: "/"
 - name: "Research"
   link: "research"
 - name: "CV"
   link: "CV_Rashkovetskyi.pdf"
 - name: "Contact"
   link: "contact"
