remote_theme: ankitsultana/researcher@gem

title: Michael 'Misha' Rashkovetskyi
author: Michael Rashkovetskyi
description: Michael 'Misha' Rashkovetskyi's personal site
baseurl: ""

markdown: kramdown
ins_logo: ""

favicon: true
favicon_location: observatory.svg

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana/researcher"
footer_text: "Based on researcher jekyll template"

sass:
    style: compressed

nav:
 - name: "About"
   link: "/"
 - name: "Research"
   link: "research"
 - name: "Outreach"
   link: "outreach"
 - name: "CV"
   link: "files/CV_Rashkovetskyi.pdf"
 - name: "Bio"
   link: "bio"
 - name: "Contact"
   link: "contact"
